// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpfylbpxtktyatsgfgej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwZnlsYnB4dGt0eWF0c2dmZ2VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0Mjc2NjQsImV4cCI6MjA2MzAwMzY2NH0.7Ed9HOC1vaNWzZybCGq-SnDQJ8kTmUuEutvU69jsGEw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);